CREATE DATABASE IF NOT EXISTS helpDeskTI;

USE helpDeskTI;

CREATE TABLE ChamadoTI(
	id INT AUTO_INCREMENT PRIMARY KEY,
	solicitante VARCHAR(250) NOT NULL,
	setor VARCHAR(250) NOT NULL,
	descricao_problema VARCHAR(260) NOT NULL,
	data_abertura TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	prioridade VARCHAR(250) NOT NULL,
	status VARCHAR(250) NOT NULL
);
CREATE TABLE TECNICO_TI(
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(250) NOT NULL UNIQUE,
	turno VARCHAR(250) NOT NULL
);